FROM hseeberger/scala-sbt:8u222_1.3.4_2.12.10

RUN apt-get install -y curl \
  && curl -sL https://deb.nodesource.com/setup_9.x | bash - \
  && apt-get install -y nodejs \
  && curl -L https://www.npmjs.com/install.sh | sh


RUN npm i nearley@2.16.0

EXPOSE 8080
